export const SET_SINGLE_CRYPTO_CURRENCIES_REQUEST =
  'SET_SINGLE_CRYPTO_CURRENCIES_REQUEST'
export const SET_SINGLE_CRYPTO_CURRENCIES_SUCCESS =
  'SET_SINGLE_CRYPTO_CURRENCIES_SUCCESS'
export const SET_SINGLE_CRYPTO_CURRENCIES_ERROR =
  'GSET_SINGLE_CRYPTO_CURRENCIES_ERROR'
