export const SET_CRYPTO_CURRENCIES_REQUEST = 'SET_CRYPTO_CURRENCIES_REQUEST'
export const SET_CRYPTO_CURRENCIES_SUCCESS = 'SET_CRYPTO_CURRENCIES_SUCCESS'
export const SET_CRYPTO_CURRENCIES_ERROR = 'SET_CRYPTO_CURRENCIES_ERROR'
